config/routes.rb
Rails.application.routes.draw do

  resources :transactions
  resources :how_it_works
  resources :users, only: [:index]

  devise_for :users

  root to: "users#index"

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

	belongs_to :init_user, :class_name => "User", :foreign_key => "initiator"
	belongs_to :joke_user, :class_name => "User", :foreign_key => "jokester"

	validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 3}
	validates :comment, presence: true, length: { maximum: 141 }

end

app/models/user.rb
class User < ActiveRecord::Base

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	# Validate content type
	validates_attachment_content_type :avatar, :content_type => /\Aimage/
	  	
	has_many :init_transactions, :class_name => "Transaction", :foreign_key => "initiator", :dependent => :destroy
	has_many :joke_transactions, :class_name => "Transaction", :foreign_key => "jokester", :dependent => :destroy

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	# before_action :authenticate_user!
	validates :username, presence: true, uniqueness: true

	# validates :first_name, presence: true
	# validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << [:username, :first_name, :last_name]
		devise_parameter_sanitizer.for(:account_update) << [:username, :first_name, :last_name, :avatar]
	end

	
    def logging(argument)
    	logger.debug("***This is a debug message: " + argument + " ***")    	
    end

end

app/controllers/how_it_works_controller.rb
class HowItWorksController < ApplicationController

	def index
		
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # before_action :set_pin, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index]
  before_action :authenticate_user!, except: [:index]
  before_action :find_user
  
  def index
      @transactions = Transaction.where("initiator = ? or  jokester = ?", @user.id, @user.id).order("created_at DESC").page(params[:page]).per_page(10)
  end

  def show
  end

  def new
    	@transaction = Transaction.new({quantity: 1})
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)
  	@joke_user = User.find(@transaction.jokester)
  	@init_user = User.find(current_user.id)
    @transaction.initiator = current_user.id

    if @transaction.take_give == true && @init_user.token_bal < 1
    	redirect_to(new_transaction_path, notice: 'Not enough tokens to give, you need to be funnier.')
    elsif @transaction.take_give == false && @init_user.token_bal < @transaction.quantity
      redirect_to(new_transaction_path, notice: 'You can only take as many as you have!')
    elsif @transaction.take_give == false && @init_user.token_ratio < 0.25
      redirect_to(new_transaction_path, notice: 'You can only take tokens when you have a ratio of 0.25 or higher!')
    elsif @transaction.valid?
        if @transaction.take_give == true
          @joke_user.token_bal += @transaction.quantity
          @init_user.token_bal -= @transaction.quantity
          @init_user.given += @transaction.quantity
        elsif
          @joke_user.token_bal -= @transaction.quantity
          @init_user.taken += @transaction.quantity
        end
        @init_user.token_ratio = ((@init_user.given.to_f - @init_user.taken.to_f)/@init_user.token_bal).abs
        @joke_user.token_ratio = ((@joke_user.given.to_f - @joke_user.taken.to_f)/@joke_user.token_bal).abs
        @transaction.save
        @joke_user.save
        @init_user.save
      	redirect_to(users_path, notice: 'Token Transaction created successfully')
    else
      	render('new')
    end
  end

  def update

  end

  def destroy
    @transaction = Transaction.find(params[:id]).destroy
    redirect_to(transactions_url, notice: 'Transaction was successfully destroyed!')
  end

  def delete
  	@transaction = Transaction.find(params[:id])
  end

  	private
      def transaction_params
        params.require(:transaction).permit(:quantity, :take_give, :initiator, :jokester, :comment)
      end

      def find_user
        if params[:user_id]
          @user = User.find(params[:user_id])
        end
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all.order("token_bal DESC").page(params[:page]).per_page(5)

  end

  def destroy
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
	    return "" if resource.errors.empty?

	    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	    sentence = I18n.t("errors.messages.not_saved",
	                      :count => resource.errors.count,
	                      :resource => resource.class.model_name.human.downcase)

	    html = <<-HTML
	    <div id="error_explanation">
	      <h2>#{sentence}</h2>
	      <ul>#{messages}</ul>
	    </div>
	    HTML

	    html.html_safe
	end

	def devise_error_messages?
		resource.errors.empty? ? false : true
	end
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
	def transaction_error_messages(resource)
	    return "" if resource.errors.empty?

	    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	    sentence = I18n.t("errors.messages.not_saved",
	                      :count => resource.errors.count,
	                      :resource => resource.class.model_name.human.downcase)

	    html = <<-HTML
	    <div id="error_explanation">
	      <h2>#{sentence}</h2>
	      <ul>#{messages}</ul>
	    </div>
	    HTML

	    html.html_safe
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/how_it_works/index.html.erb
<%= render 'layouts/intro' %>

<h2>Deets:</h2>
<ul>
	<li>You can only give as many as you have.</li>
	<li>The amount you give is deducted from your token balance. Better be a good joke.</li>
	<li>You can only take as many as you have but it doesn't add to you token balance.</li>
	<li>You must have a (Tokens Given - Tokens Taken) to Tokens Balance ratio of at least 0.25 in order to take tokens.</li>
	<li>You must add a reason for the transaction in the comment section.</li>
</ul>

app/views/layouts/_header.html.erb
  

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to("Tokens", root_path, class: "navbar-brand") %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to("+/- Token", new_transaction_path) %></li>
            <li><%= link_to("WTF is This?", how_it_works_path) %></li>
          <% if user_signed_in? %>
            <li class="btn-group navbar-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %> <span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to("My History", transactions_path({:user_id => current_user.id})) %></li>
                  <li><%= link_to("Account Settings", edit_user_registration_path) %></li>
                  <li class="divider"></li>
                  <li><%= link_to("Log Out", destroy_user_session_path, method: :delete) %></li>
                </ul>
            </li>
          <% else %>
            <li><%= link_to("Log In", new_user_session_path) %></li>
            <li><%= link_to("Sign Up", new_user_registration_path) %></li>
          <% end %>
        </ul>
       </div> 
    </div>
  </div>
</nav>

app/views/layouts/_intro.html.erb
<div class="container text-center jumbotron">
	<h1>Make a Funny, Get a Token</h1>
	<h2>You start with 5 tokens.</h2>
	<h3>Make a good joke, get a token (or two) from a friend. <br />
	Make a bad joke, get a token (or two) taken away. <br />
	Spend wisely. Joke carefully.</h3>

	<%= link_to("Log In", new_user_session_path, class: "btn btn-default btn-lg") %>
	<%= link_to("Sign up", new_user_registration_path, class: "btn btn-primary btn-lg") %>
</div>

app/views/layouts/_tokens.html.erb
<div class="container text-center jumbotron">  
	<h1>Token Balance: <%= pluralize(current_user.token_bal, "Token") %></h1>
	<h4>(Given: <%= current_user.given %>, Taken: <%= current_user.taken %>, Ratio: <%= number_with_precision(current_user.token_ratio, precision: 2) %>)</h4>
	
	<% if current_user.token_bal < 5 %>
		<h3>Step up your game, you started with 5 for Pete's sake!</h3>
	<% elsif current_user.token_bal >= 5 && current_user.token_bal < 8 %>
		<h3>Here, <%= link_to("www.jokes.com", "http://www.jokes.com") %></h3>
	<% elsif current_user.token_bal >= 8 %>
		<h3>Killin' it.</h3>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    
    <title>Tokens</title>
    <%= stylesheet_link_tag('application', :media => 'all') %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'endless page' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
  	<div class="container">
  	<% flash.each do |name, msg| %>
  		<%= content_tag(:div, msg, class: "alert alert-success") %>
  	<% end %>
      	<%= yield %>
    </div>

  </body>
</html>

app/views/transactions/_form.html.erb
<div class="form-group">
	<%= foo.select(:take_give, [["Give", 1], ["Take", 0]], {}, { class: "form-control input-lg" }) %>
</div>

<div class="form-group">
	<%= foo.label(:quantity) %>
	<%= foo.number_field(:quantity, min: 1, max: 2, class: "form-control input-lg") %>
</div>

<div class="form-group">
	<%= foo.label(:jokester, "User") %>
   	<%= foo.select(:jokester, User.where.not(id: current_user.id).collect {|u| [u.username + " (" + u.token_bal.to_s + ")", u.id] }, {}, { class: "form-control input-lg" } ) %>
</div>



<div class="form-group">
	<%= foo.label(:comment, "Comment") %>
    <%= foo.text_area(:comment, class: "form-control input-lg") %>
</div>

app/views/transactions/delete.html.erb
<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(:transaction, :url => {:action => 'destroy', :id => @transaction.id}) do |f| %>

    <p>Are you sure you want to permanently delete this transaction?</p>

      <th>Quantity</th>
      <th>Take/Give</th>
      <th>From User</th>
      <th>To User</th>
      <th>Comment</th>
    </tr>
    <% @transactions.each do |t| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= t.quantity %></td>
      <td class="center"><%= t.take_give %></td>
      <td class="center"><%= t.from_user_id %></td>
      <td class="center"><%= t.to_user_id %></td>
      <td class="center"><%= t.comment %></td>

    <div class="form-buttons">
      <%= submit_tag("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/transactions/index.html.erb
<%= link_to "Home", root_path %>
<% if user_signed_in? %>
    <%= render 'layouts/tokens' %>
<% else %>
    <%= render 'layouts/intro' %>
<% end %>


<div class="container text-center">
  <div class="row">
  	
	<h2><%= @user.username %>'s History</h2>
	<h4>(Balance: <%= @user.token_bal %>, Given: <%= @user.given %>, Taken: <%= @user.taken %>, Ratio: <%= number_with_precision(@user.token_ratio, precision: 2) %>)</h4>
  </div>


	<% if @transactions.blank? %>
		<h3>No Love...</h3>
	<% else %>
	<%= will_paginate @transactions, :page_links => false %>
	<div class="panel panel-default">
		<div class="table-responsive">
			<table id="transactions-table" class="table table-hover">
			  	<% @transactions.each do |t| %>
				    <tr>
				    	<td id="date"><%= t.created_at.strftime("%b %d, %Y at %H:%M:%S %Z") %></td>
						<td id="user-transaction-info">
							<%= link_to(t.init_user.username, transactions_path({:user_id => t.init_user.id})) if t.init_user %>
							<% if t.take_give == true %>
								 gave
							<% else %>
								  took
							<% end %>

							<%= pluralize(t.quantity, "Token") %>

							<% if t.take_give == true %>
								 to 
							<% else %>
								 from 
							<% end %>

							<%= link_to(t.joke_user.username, transactions_path({:user_id => t.joke_user.id})) if t.joke_user %>
						</td>
						<td id="comment"><%= t.comment %></td>
				    </tr>
			    <% end %>
		  	</table>
		</div>
	<% end %>
</div>

app/views/transactions/new.html.erb
<%= render 'layouts/tokens' %>

  <h2>What To Do?</h2>

  <%= form_for(:transaction, :url => {:action => 'create'}) do |f| %>
	<%= transaction_error_messages(@transaction) %>

    <%= render(:partial => "form", :locals => {:foo => f}) %>

    <div class="form-buttons">
      <%= submit_tag("Create Transaction", class: "btn btn-primary btn-lg") %>
      <%= link_to "Cancel", :back, class: "btn btn-secondary btn-lg" %>
    </div>

  <% end %>

app/views/users/index.html.erb
<% if user_signed_in? %>
    <%= render 'layouts/tokens' %>
<% else %>
    <%= render 'layouts/intro' %>
<% end %>

<div class="container text-center">
  <div class="row">
    <h2>Funny People</h2>
  </div>
  <%= will_paginate @user, :page_links => false %>
   <div class="panel panel-default">
    <div class="table-responsive">
        <table id="users-table" class="table table-hover">
            <tr>
              <td>&nbsp;</td>
              <td><h4>Username</h4></td>
              <td class="text-center"><h4>Token Balance</h4></td>
            </tr>
          <% @users.each do |u| %>
            <tr>
              <td><%= image_tag(u.avatar.url(:thumb)) %></td>
              <td>
                <h3><%= link_to(u.username, transactions_path({:user_id => u.id})) %></h3>
                <h4>(Given: <%= u.given %>, Taken: <%= u.taken %>)</h4>
              </td> 
              <td class="text-center">
                <h3><%= pluralize(u.token_bal, "Token") %></h3>
                <h4>(Ratio: <%= number_with_precision(u.token_ratio, precision: 2) %>)</h4>
              </td>
            </tr>
          <% end %>
        </table>
        
      </div>
    </div>
      
  </div>
    
    
</div>